
<? PHP
ini_set ( "display_errors" , 1 );
сообщение об ошибке ( E_ALL );
ini_set ( 'display_startup_errors' , 1 );

require_once ( "classes / base.php" );
require_once ( CLASSES_PATH . "Ub / Callback / Callback.php" );
$ callback = new  UbCallbackCallback ();
$ callback -> run ();
