
npx @vkontakte/create-vk-mini-app vk-apps-currency
cd vk-apps-currency
npm start
<!DOCTYPE html> <html lang="en">  <head>    <meta charset="utf-8">    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, viewport-fit=cover">    <meta name="theme-color" content="#000000">    <meta content="IE=Edge" http-equiv="X-UA-Compatible">    <title>VK App Boilerplate</title>  </head>  <body>    <div id="root"></div>  </body> </html>i
ngrok http 10888
npm install gh-pages --save-dev
"homepage": "https://ilyapishchulin.github.io/vk-apps-currency/"
